# Site settings
title: My Blog
description: A blog about programming and technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yehleien.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation links
nav:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Categories
    url: /categories.html

# Default theme settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
      categories: ["uncategorized"]
      tags: []
